// Cultural and literary deep-reading add-on.
// Loaded after explanation-layout.js: decorates the existing insight rows without changing the core reader.
window.KIEU_CULTURAL_LAYERS={
  1:{sourceCompare:{title:'NGUYỄN DU ĐÃ ĐỔI GÌ TỪ TRUYỆN NGUỒN?',text:'Phần mở đầu mang tính triết luận này không chỉ kể cốt truyện. Nghiên cứu đối chiếu cho thấy Nguyễn Du chuyển những lời bình quanh truyện nguồn thành một mở đầu trữ tình về tài, mệnh và trải nghiệm đời người — đặt “cách đọc” cho toàn bộ tác phẩm trước khi Kiều xuất hiện.',url:'https://nguyendu.com.vn/m/vi/s0-sanh-truyen-kieu-voi-kim-van-kieu-truyen-80ABB21C14FF53448807514B5C0E8919.html'}},
  41:{technique:{name:'CHẤM PHÁ + TƯƠNG PHẢN MÀU',text:'Một nền xanh gần như vô tận chỉ được “điểm” vài bông lê trắng. Ít nét nhưng không gian mở rất rộng; chữ “điểm” làm hoa trắng nổi lên như nét bút trên tranh.'},motif:{name:'HOA',text:'“Hoa” trong Kiều khi là cảnh thật, khi thành ẩn dụ cho sắc đẹp, tuổi xuân và thân phận. Ở đây hoa còn vô tư, tươi trẻ — trước khi hình ảnh hoa dần gắn với tổn thương của Kiều.',links:[{target:175,label:'Hải đường khi Kiều tương tư'},{target:845,label:'“Một đóa trà mi” khi Kiều bị xúc phạm'}]},sourceCompare:{title:'THI LIỆU ĐƯỢC VIỆT HÓA',text:'Hai câu xuân này tiếp nhận thi liệu cổ “phương thảo liên thiên bích / lê chi sổ điểm hoa”, nhưng qua lục bát và lựa chọn từ Việt, cảnh trở nên tự nhiên, sáng và rất dễ hình dung.',url:'https://nguyendu.com.vn/m/vi/ve-cac-ban-dich-truyen-kieu-ra-trung-van-23947C2341D956D283CBF1B8E2D0518C.html/i1435748095363/5/10'}},
  43:{culture:{title:'THANH MINH · TẢO MỘ · ĐẠP THANH',text:'Thanh minh vừa có phần lễ (sửa sang, viếng mộ, đốt vàng mã) vừa có phần hội (đi chơi xuân). Vì thế việc chị em Kiều đi giữa đám đông vui xuân rồi gặp một ngôi mộ vô chủ không phải ngẫu nhiên: ngay trong ngày tưởng nhớ người chết, Đạm Tiên bị bỏ quên trở thành một nghịch cảnh rất mạnh.'}},
  55:{technique:{name:'TẢ CẢNH NGỤ TÌNH · CHUYỂN SẮC',text:'Sau cảnh hội xuân đông vui, nhịp thơ chậm lại bằng “nao nao”, “nho nhỏ”. Cảnh vẫn đẹp nhưng bắt đầu mang cảm giác bâng khuâng; đó là chiếc cầu chuyển từ niềm vui sang vùng mộ Đạm Tiên.'},motif:{name:'NƯỚC',text:'Nước trong Kiều thường đi cùng chuyển động của đời và tâm trạng: lúc trong veo, lúc sóng gió, lúc thành sông Tiền Đường. Ở đây dòng nước chỉ mới “nao nao” — một bất an rất nhẹ trước biến cố.',links:[{target:169,label:'Nước trong veo sau lần gặp Kim'},{target:2639,label:'Tiền Đường ở đoạn bi kịch cuối lưu lạc'}]}},
  83:{technique:{name:'KHÁI QUÁT HÓA TỪ MỘT SỐ PHẬN',text:'Kiều vừa nghe chuyện một người cụ thể là Đạm Tiên nhưng lập tức nâng nó thành “phận đàn bà” và “lời chung”. Câu thơ vì vậy vượt khỏi chức năng kể chuyện để thành nhận xét xã hội.'},living:{title:'CÂU KIỀU ĐÃ RA KHỎI TRUYỆN',text:'Ngày nay cặp “Đau đớn thay phận đàn bà / Lời rằng bạc mệnh cũng là lời chung” thường được trích để nói về bất công hay khổ đau của phụ nữ. Trong ngữ cảnh gốc, nó nảy ra ngay trước một ngôi mộ bị bỏ quên — nghĩa là sự khái quát bắt đầu từ lòng thương một người cụ thể.'},sourceCompare:{title:'NGUYỄN DU MỞ RỘNG ĐIỂM NHÌN',text:'Nghiên cứu so sánh cách ứng xử của Kiều lưu ý rằng lời than trong Truyện Kiều không còn chỉ dành cho Đạm Tiên: Nguyễn Du cho Kiều nhìn thấy một số phận chung của phụ nữ. Đây là ví dụ rõ về việc tăng chiều sâu trữ tình và nhân đạo so với kể sự thuần túy.',url:'https://nguyendu.com.vn/m/vi/su-khac-biet-trong-cach-ung-xu-cua-nhan-vat-thuy-kieu-trong-kim-van-kieu-truyen-truyen-kieu-48F7756E80D956458173057564ECF295.html/i1435748095363/5/51'}},
  164:{technique:{name:'ĐỐI LẬP TRONG / NGOÀI',text:'“Tình trong” đã rõ nhưng “mặt ngoài” vẫn e: một câu ngắn đặt cảm xúc bên trong đối diện khuôn phép biểu hiện bên ngoài. Chính độ lệch ấy tạo cảm giác tình yêu vừa nảy sinh nhưng chưa thể nói thẳng.'},living:{title:'CÁCH DÙNG HIỆN NAY',text:'“Tình trong như đã, mặt ngoài còn e” thường được dùng cho hai người có cảm tình với nhau nhưng chưa công khai. Trong truyện, nó xảy ra ngay lần Kim và Kiều vừa nhìn thấy nhau, nên cái “đã” ở đây rất nhanh, còn cái “e” thuộc về lễ giáo và sự dè dặt.'}},
  631:{technique:{name:'CHÂM BIẾM BẰNG MỘT ĐỘNG TỪ',text:'Nguyễn Du không cần gọi Mã Giám Sinh là vô lễ; chữ “tót” tự làm việc đó. Động tác nhanh, trịch thượng đặt cạnh vẻ “bảnh bao” trước đó làm lớp vỏ người có học rạn ngay lập tức.'},culture:{title:'GHẾ TRÊN VÀ TRẬT TỰ LỄ NGHI',text:'Trong một cuộc gặp mang danh hỏi cưới, vị trí ngồi và cách ngồi đều biểu thị vai vế, lễ độ. Mã tự nhiên chiếm ghế trên và “ngồi tót” nên hành vi của hắn lệch hẳn vai một người đến cầu hôn tử tế.'}},
  647:{technique:{name:'TỪ VỰNG THỊ TRƯỜNG PHÁ VỠ NGÔN NGỮ HÔN LỄ',text:'Trước đó là “mua ngọc”, “sính nghi” — những chữ nghe sang và có vẻ cưới hỏi. Đến “cò kè”, “ngã giá”, ngôn ngữ thật của giao dịch lộ ra. Cú chuyển từ lễ nghi sang mặc cả là cách Nguyễn Du bóc lớp ngụy trang.'},culture:{title:'HÔN LỄ BỊ DÙNG LÀM VỎ CHO MUA BÁN',text:'Các chữ “sính nghi”, “nạp thái”, “vu quy”, “canh thiếp” vốn thuộc nghi thức hôn nhân. Ở đây chúng che một giao dịch mua người. Hiểu lớp nghi lễ này mới thấy sự cay đắng: hình thức là cưới, cơ chế thực tế là định giá Kiều.'},living:{title:'“CÒ KÈ BỚT MỘT THÊM HAI”',text:'Cụm này ngày nay có thể được dùng vui để nói chuyện mặc cả. Nhưng trong ngữ cảnh gốc, điều bị mặc cả là một con người; vì thế sắc thái câu thơ lạnh và nhục nhã hơn nhiều cách dùng đời thường hiện nay.'}},
  665:{sourceCompare:{title:'NGUYỄN DU NÉN MỘT KHỐI KỂ SỰ RẤT DÀI',text:'Nghiên cứu đối chiếu cho thấy hồi 5–6 của Kim Vân Kiều truyện dành nhiều chi tiết cho tranh luận gia đình, thư từ, giấy nhận tiền và thủ tục bán mình. Nguyễn Du thu gọn mạnh, đặc biệt quanh câu 665–684, để dồn trọng tâm vào máu mắt của cha và lựa chọn hiếu–tình của Kiều.',url:'https://nguyendu.com.vn/vi/s0-sanh-truyen-kieu-voi-kim-van-kieu-truyen-80ABB21C14FF53448807514B5C0E8919.html/i1437725901799/6/21'}},
  690:{technique:{name:'THÀNH NGỮ HÓA MỘT CƠ CHẾ XÃ HỘI',text:'“Đổi trắng thay đen” biến sự bất công thành hình ảnh cực ngắn: tiền không chỉ mua việc, nó có thể làm sự thật bị đảo ngược.'},culture:{title:'CHẠY ÁN VÀ QUYỀN LỰC TIỀN',text:'Ngay trước đó, Chung công tính khoảng ba trăm lạng để “việc này mới xuôi”. Câu 690 nối trực tiếp tiền với khả năng bẻ hướng vụ án, cho thấy tai họa nhà Kiều không chỉ là số phận mà còn là một cơ chế tham nhũng cụ thể.'},living:{title:'CỤM TỪ VẪN SỐNG TRONG TIẾNG VIỆT',text:'“Đổi trắng thay đen” hiện vẫn được dùng cho việc xuyên tạc đúng–sai. Trong Kiều, nó đứng cạnh “đồng tiền”, nên nghĩa gốc ở đoạn này đặc biệt gắn với quyền lực của tiền trong công lý.'}},
  1519:{technique:{name:'PHÉP ĐỐI · NGƯỜI ĐI / KẺ Ở',text:'“Người lên ngựa / kẻ chia bào” chia một câu thơ thành hai nửa song song. Cấu trúc cân đối nhưng hai nhân vật lại chuyển theo hai hướng khác nhau, khiến chính hình thức câu thơ mang cảm giác chia lìa.'},motif:{name:'ĐƯỜNG XA / MÙA THU',text:'Quan san, dặm hồng, ngàn dâu biến khoảng cách tình cảm thành không gian nhìn thấy được. Mùa thu không chỉ là thời tiết; màu rừng phong trở thành “màu” của biệt ly.',links:[{target:1525,label:'Vầng trăng bị “xẻ làm đôi”'},{target:2873,label:'Quan san xuất hiện lại ở một chuyến đi xa khác'}]}},
  1525:{technique:{name:'ẨN DỤ THỊ GIÁC · MỘT TRĂNG, HAI NƠI',text:'Trăng vốn là một vật chung cho hai người, nhưng Kiều tưởng tượng nó bị “xẻ làm đôi”: nửa ở gối chiếc, nửa trên dặm trường. Một hình ảnh không thể có trong thực tế lại diễn tả rất đúng cảm giác tình cảm bị chia cắt.'},motif:{name:'TRĂNG',text:'Trăng từng chứng lời thề Kim–Kiều; ở đây trăng lại chứng một cuộc chia ly. Cùng một motif nhưng chức năng đổi từ gắn kết sang phân cách.',links:[{target:449,label:'Trăng làm chứng lời thề Kim–Kiều'},{target:3224,label:'Trăng trong đời sống tri kỷ cuối truyện'}]}},
  3251:{technique:{name:'ĐẢO TRỌNG TÂM TỪ MỆNH SANG TÂM',text:'Sau hàng nghìn câu nói về tài, mệnh, nghiệp và phong trần, đoạn kết đặt “thiện căn” trong lòng người. Đây là cú đổi trọng tâm: số phận giải thích điều con người gặp, nhưng “tâm” đánh giá cách con người sống.'},living:{title:'“CHỮ TÂM KIA MỚI BẰNG BA CHỮ TÀI”',text:'Câu kết này thường được trích như một châm ngôn đạo đức độc lập. Đặt lại vào toàn truyện, nó không phủ nhận tài năng; nó xuất hiện sau khi người đọc đã thấy tài năng không cứu Kiều khỏi đau khổ, còn lòng người nhiều lần quyết định nàng được cứu hay bị hại.'}}
};
window.culturalLayersForLine=function(lineNumber){return window.KIEU_CULTURAL_LAYERS[lineNumber]||null};
function culturalSourceLink(item){return item.url?`<a class="culture-source" href="${escapeHtml(item.url)}" target="_blank" rel="noopener">Nguồn ↗</a>`:''}
function culturalRow(label,item,extraClass=''){if(!item)return '';const title=item.name||item.title||label;return `<div class="reader-insight-row cultural-layer ${extraClass}"><div class="insight-label-line"><b>${escapeHtml(label)}</b>${culturalSourceLink(item)}</div><strong>${escapeHtml(title)}</strong><p>${escapeHtml(item.text)}</p></div>`}
function motifRow(motif){if(!motif)return '';const links=(motif.links||[]).map(link=>`<a class="verse-jump" data-target-line="${link.target}" href="#cau-${link.target}">${escapeHtml(link.label)} · câu ${link.target}</a>`).join('');return `<div class="reader-insight-row cultural-layer motif-layer"><b>MOTIF LẶP LẠI</b><strong>${escapeHtml(motif.name)}</strong><p>${escapeHtml(motif.text)}</p>${links?`<div class="motif-links">${links}</div>`:''}</div>`}
const previousReaderInsightPieces=readerInsightPieces;
readerInsightPieces=function(line){const pieces=previousReaderInsightPieces(line),layer=window.culturalLayersForLine(line.n);if(!layer)return pieces;if(layer.technique)pieces.push(culturalRow('BÚT PHÁP / PHÉP TU TỪ',layer.technique,'technique-layer'));if(layer.motif)pieces.push(motifRow(layer.motif));if(layer.culture)pieces.push(culturalRow('BỐI CẢNH XÃ HỘI',layer.culture,'culture-context-layer'));if(layer.living)pieces.push(culturalRow('CÂU KIỀU TRONG ĐỜI SỐNG',layer.living,'living-layer'));if(layer.sourceCompare)pieces.push(culturalRow('SO VỚI NGUỒN / THI LIỆU',layer.sourceCompare,'source-compare-layer'));return pieces};
renderPage({scroll:false});
