// Cross-scene reading layers for selected Truyện Kiều verses.
// These notes complement per-line meanings: they track voice, information asymmetry,
// long-range echoes, Kiều's psychological arc, and materially different textual variants.
window.KIEU_PSYCHOLOGY_TIMELINE=[
 {range:[15,38],stage:"Bình yên có dự cảm",text:"Kiều xuất hiện trong một đời sống được bảo bọc, nhưng lời mở đầu về tài–mệnh đã đặt bóng bi kịch lên tài sắc của nàng."},
 {range:[39,244],stage:"Đồng cảm rồi ám ảnh",text:"Từ thương Đạm Tiên, Kiều bắt đầu nhìn số phận người bạc mệnh như một khả năng có thể ứng vào chính mình."},
 {range:[245,572],stage:"Hy vọng và chủ động yêu",text:"Kiều chủ động đáp lại Kim Trọng, thề nguyền và đặt niềm tin vào khả năng con người giữ được tình trước số phận."},
 {range:[573,804],stage:"Xé đôi giữa tình và hiếu",text:"Gia biến buộc Kiều hy sinh tình riêng. Nàng cố dùng lý trí để biến mất mát của mình thành nghĩa vụ có thể sắp xếp và trao gửi."},
 {range:[805,1056],stage:"Mất quyền tự chủ, phản kháng",text:"Bị biến thành món hàng và lừa vào lầu xanh, Kiều phản kháng đến mức tìm cái chết để giành lại quyền quyết định cuối cùng."},
 {range:[1057,1274],stage:"Hy vọng thoát thân rồi bị phản bội",text:"Hy vọng vào Sở Khanh nhanh chóng biến thành một cú phản bội, khiến Kiều hiểu sâu hơn cơ chế dụ dỗ và cưỡng ép đang vây mình."},
 {range:[1275,1526],stage:"Tạm hồi phục trong tình cảm",text:"Với Thúc Sinh, Kiều có một quãng được yêu và được chuộc khỏi lầu xanh, nhưng sự an toàn này phụ thuộc vào một quan hệ vốn không cân bằng."},
 {range:[1527,2032],stage:"Sợ hãi, nhẫn nhịn, tự bảo toàn",text:"Dưới quyền Hoạn Thư, Kiều phải đọc tình thế, nhịn, lánh và tìm đường sống; khả năng tự bảo toàn trở thành quan trọng hơn việc thắng thua tức thời."},
 {range:[2033,2164],stage:"Kiệt quệ và tìm nơi nương tựa",text:"Kiều tìm cửa Phật như một lối ra khỏi vòng mua bán, nhưng rồi vẫn bị kéo trở lại vào mạng lưới lừa gạt."},
 {range:[2165,2418],stage:"Phục hồi quyền tự quyết",text:"Gặp Từ Hải, Kiều lần đầu có quyền lực đủ lớn để trả ơn, hỏi tội và thử tái lập một trật tự công bằng theo ký ức của mình."},
 {range:[2419,2738],stage:"Hy vọng ổn định rồi tội lỗi, tuyệt vọng",text:"Kiều tin vào khả năng chiêu an đem lại kết thúc ổn định; khi Từ Hải chết, niềm tin ấy biến thành mặc cảm và tuyệt vọng."},
 {range:[2739,2972],stage:"Lắng lại sau biến cố",text:"Sau Tiền Đường và cửa Phật, Kiều sống trong trạng thái rút khỏi đời thế tục, trong khi gia đình vẫn tìm kiếm nàng."},
 {range:[2973,3188],stage:"Đoàn tụ nhưng giữ ranh giới",text:"Niềm vui gặp lại không xóa chấn thương. Kiều chủ động định nghĩa lại chữ trinh, hôn nhân và giới hạn thân thể của mình trong cuộc đoàn tụ."},
 {range:[3189,3254],stage:"Hòa giải và buông khúc bạc mệnh",text:"Tiếng đàn đổi từ sầu sang vui; quan hệ với Kim trở thành tri kỷ và đoạn kết chuyển từ số mệnh sang chữ tâm."}
];
window.KIEU_NARRATIVE_LAYERS={
1:{voice:{kind:"LỜI NGƯỜI KỂ",text:"Đây là lời mở đầu ở cấp độ tác giả/người kể, chưa phải suy nghĩ của Kiều. Nó đặt một luận đề bao trùm trước khi nhân vật xuất hiện."},connections:[{type:"echo",target:3241,label:"Vọng lại ở đoạn kết",text:"Đoạn kết quay lại cùng câu hỏi về trời, mệnh và trách nhiệm con người, tạo thành khung tư tưởng ôm trọn câu chuyện."}]},
2:{voice:{kind:"LỜI NGƯỜI KỂ",text:"Cặp tài–mệnh được nêu như một nhận xét khái quát về đời người; về sau cuộc đời Kiều trở thành trường hợp thử nghiệm cho nhận xét này."},variant:{base:"Chữ tài chữ mệnh khéo là ghét nhau",alternate:"Chữ tài chữ sắc khéo là ghét nhau",effect:"Đọc “mệnh” tạo trục xung đột tài năng ↔ số phận, đúng với luận đề xuyên suốt tác phẩm. Đọc “sắc” chuyển câu sang quan hệ tài ↔ sắc, làm yếu hẳn lớp triết lý về định mệnh.",note:"Văn bản gốc của Nguyễn Du đã thất truyền; dị bản cần được hiểu là lịch sử truyền bản, không phải bằng chứng chắc chắn về chữ nguyên tác.",source:{label:"Khảo luận dị bản",url:"https://danviet.vn/su-co-dam-tien-chuyen-gioi-trong-truyen-kieu-sai-tu-ban-thao-7777620163-d387676.html"}}},
4:{variant:{base:"Những điều trông thấy mà đau đớn lòng",alternate:"Những điều trông thấy đã đau đớn lòng",effect:"“Mà” làm quan hệ giữa điều mắt thấy và nỗi đau mang sắc thái nối–nhấn, gần một lời cảm thán. “Đã” nhấn trạng thái đau xảy ra sau trải nghiệm, thiên về thời–kết quả hơn.",note:"Bản Kiều Oánh Mậu 1902 trên Nôm Foundation ghi “đã”.",source:{label:"Kiều Oánh Mậu 1902",url:"https://www.nomfoundation.org/nom-project/tale-of-kieu/tale-of-kieu-version-1902?uiLang=en"}}},
6:{variant:{base:"Trời xanh quen thói má hồng đánh ghen",alternate:"Trời xanh quen với má hồng đánh ghen",effect:"“Quen thói” nhân hóa Trời như có một thói quen đáng trách, khiến giọng phê phán sắc hơn. “Quen với” giảm nét kết tội ấy và làm quan hệ cú pháp khác đi.",note:"Bản Kiều Oánh Mậu 1902 chép “quen với”.",source:{label:"Kiều Oánh Mậu 1902",url:"https://www.nomfoundation.org/nom-project/tale-of-kieu/tale-of-kieu-version-1902?uiLang=en"}}},
8:{variant:{base:"Phong tình cổ lục còn truyền sử xanh",alternate:"Phong tình có lục còn truyền sử xanh",effect:"“Cổ lục” gợi một sách/ghi chép cũ về chuyện tình; “có lục” chỉ nói rằng chuyện ấy có ghi chép. Một chữ đổi làm nguồn kể mang sắc thái cổ thư rõ hay nhạt đi.",note:"Bản Kiều Oánh Mậu 1902 chép “có lục”.",source:{label:"Kiều Oánh Mậu 1902",url:"https://www.nomfoundation.org/nom-project/tale-of-kieu/tale-of-kieu-version-1902?uiLang=en"}}},
83:{voice:{kind:"LỜI KIỀU HÒA VÀO LỜI KỂ",text:"Lời than về “phận đàn bà” phát ra từ cảm xúc của Kiều nhưng mang độ khái quát lớn đến mức rất gần một lời bình của người kể. Đây là chỗ ranh giới giọng nhân vật và giọng tác giả trở nên mờ."},knowledge:"Kiều chỉ biết câu chuyện Đạm Tiên vừa nghe, nhưng người đọc đã được phần mở đầu báo trước về tài–mệnh. Vì thế người đọc thấy lời thương Đạm Tiên đồng thời như một dự báo mà Kiều chưa thể kiểm chứng.",connections:[{type:"foreshadow",target:409,label:"Từ thương người đến lo cho mình",text:"Khi nói với Kim, Kiều sẽ trực tiếp nhắc lời tướng số về tài hoa và bạc mệnh, biến nỗi thương Đạm Tiên thành nỗi sợ cho chính mình."}],psychology:{stage:"Đồng cảm → tự ám thị",text:"Kiều không dừng ở thương người chết; nàng bắt đầu dùng câu chuyện ấy để hình dung tương lai của mình."}},
409:{voice:{kind:"LỜI KIỀU NÓI TRỰC TIẾP",text:"Kiều đáp lời Kim Trọng và tự đối chiếu số phận hai người. Đây không phải lời tiên tri khách quan của người kể mà là cách Kiều đã nội tâm hóa dự cảm tài–mệnh."},knowledge:"Kim biết Kiều lo sợ số phận nhưng chưa biết gia biến sắp xảy ra; Kiều biết lời tướng số từ nhỏ; người đọc đã có thêm dấu hiệu Đạm Tiên nên cảm nhận nguy cơ mạnh hơn cả hai nhân vật.",connections:[{type:"foreshadow",target:723,label:"Nỗi sợ thành biến cố thật",text:"Điều Kiều chỉ lo ở đây sẽ trở thành đứt gãy cụ thể khi nàng phải cậy Vân nối duyên với Kim."}],psychology:{stage:"Yêu nhưng đã sợ mất",text:"Ngay trong thời điểm hạnh phúc nhất, Kiều vẫn không thể hoàn toàn tin rằng hạnh phúc ấy sẽ bền."}},
441:{voice:{kind:"LỜI KIỀU NÓI TRỰC TIẾP",text:"Kiều chủ động giải thích vì sao nàng trở lại gặp Kim trong đêm và chấp nhận cùng chàng đi tới lời thề."},knowledge:"Kiều và Kim biết lời thề bí mật; gia đình hai bên chưa biết. Người đọc lại mang theo dự cảm Đạm Tiên và lời tướng số, nên lời thề vừa lãng mạn vừa căng vì biết điều gì đó có thể phá vỡ nó.",connections:[{type:"foreshadow",target:723,label:"Lời thề trở thành món nợ",text:"Khi gia biến xảy ra, chính lời thề này khiến Kiều phải “trao duyên” thay vì đơn giản chấm dứt tình yêu."},{type:"echo",target:3225,label:"Duyên được định nghĩa lại",text:"Cuối truyện, lời nguyện không được hoàn thành theo hình thức vợ chồng thông thường mà chuyển thành quan hệ tri kỷ."}],psychology:{stage:"Chủ động chọn tình yêu",text:"Kiều biết mình đang vượt khuôn phép nhưng vẫn chủ động lựa chọn và đặt lời hứa vào mối tình."}},
723:{voice:{kind:"LỜI KIỀU NÓI TRỰC TIẾP",text:"Đây là lời cầu xin có tính nghi lễ với Thúy Vân, không phải lời người kể. Các động tác “lạy”, “thưa” làm lời nói thành một hành vi chuyển giao nghĩa vụ."},knowledge:"Kiều biết đầy đủ lời thề với Kim và quyết định bán mình; Vân chỉ bắt đầu được trao phần câu chuyện cần thiết để nhận lời; Kim vắng mặt nên hoàn toàn chưa biết tình yêu của mình đang được Kiều sắp xếp lại.",connections:[{type:"callback",target:441,label:"Trả món nợ từ lời thề",text:"“Trao duyên” chỉ đau đến vậy vì trước đó hai người đã chủ động thề nguyền với nhau."},{type:"foreshadow",target:3225,label:"Không thể trả tình yêu như một món đồ",text:"Cuối truyện, Kiều và Kim phải tự định nghĩa một hình thức gắn bó khác, cho thấy món nợ tình không thể được giải quyết hoàn toàn bằng việc chuyển duyên cho Vân."}],psychology:{stage:"Đau đớn nhưng ép mình điều hành mất mát",text:"Kiều biến đau riêng thành một chuỗi việc phải xử lý: cứu cha, cậy em, trả nghĩa Kim. Lý trí hoạt động mạnh chính vì cảm xúc quá lớn."}},
1533:{voice:{kind:"LỜI KỂ ĐẶT TIÊU ĐIỂM VÀO HOẠN THƯ",text:"Đoạn này chủ yếu do người kể dựng hành động và thế cờ của Hoạn Thư; không nên đọc mọi câu như lời Hoạn Thư nói trực tiếp."},knowledge:"Hoạn Thư đã biết chuyện Thúc Sinh–Kiều và có thời gian chuẩn bị cách xử lý. Thúc Sinh không biết hết kế hoạch của vợ; Kiều lại càng ít thông tin hơn. Chênh lệch thông tin chính là một phần quyền lực của Hoạn Thư.",connections:[{type:"foreshadow",target:2365,label:"Những gì Hoạn Thư làm sẽ thành lời bào chữa",text:"Đến cuộc báo oán, Hoạn Thư sẽ chọn chính những lần mình nương tay và hành xử có vẻ đúng phép để tự cứu."}],psychology:{stage:"Kiều chuyển sang chế độ sinh tồn",text:"Trước một đối thủ nắm cả quyền gia đình lẫn thông tin, mục tiêu của Kiều dần từ giữ tình yêu sang giữ an toàn và tìm đường thoát."}},
2365:{voice:{kind:"LỜI HOẠN THƯ NÓI TRỰC TIẾP",text:"Đây là màn tự biện hộ. Hoạn Thư chủ động nhận phần lỗi ai cũng biết rồi lập tức tái kể quá khứ theo hướng có lợi cho mình."},knowledge:"Kiều biết toàn bộ tổn thương mình từng chịu; Hoạn Thư biết Kiều đang có quyền phán xét và biết những chi tiết nào có thể làm Kiều chùn tay; người đọc nhớ cả sự tàn nhẫn lẫn những lần Hoạn Thư để đường sống.",connections:[{type:"callback",target:1533,label:"Quay lại cách Hoạn Thư đã điều khiển tình thế",text:"Sự khôn ngoan trong lời bào chữa là cùng một kiểu quyền lực gián tiếp đã xuất hiện khi nàng xử lý chuyện Thúc Sinh–Kiều."}],psychology:{stage:"Có quyền nhưng phải quyết định mình sẽ dùng quyền thế nào",text:"Kiều không còn là người bị xử; nàng phải chọn giữa trả thù tuyệt đối và một kiểu công bằng biết cân nhắc tình tiết."}},
2465:{voice:{kind:"LỜI KỂ CHÍNH TRỊ",text:"Người kể chuyển ngôn ngữ sang chiêu an, danh phận, triều đình và thế lực. Đây là một cuộc mặc cả quyền lực hơn là hội thoại tình cảm."},knowledge:"Hồ Tôn Hiến và phía triều đình biết chiêu hàng là chiến lược làm yếu Từ Hải; Từ và Kiều nghe lời hứa về danh phận, ổn định. Người đọc được người kể cho thấy sự bất cân xứng nên có lý do nghi ngờ lời hứa trước nhân vật.",connections:[{type:"foreshadow",target:2499,label:"Lời hứa đổi thành thế bí",text:"Khi Từ Hải hạ cảnh giác, lợi thế quân sự và chính trị đổi chiều rất nhanh."}],psychology:{stage:"Kiều khao khát một lối thoát ổn định",text:"Sau quá nhiều năm lưu lạc, lời hứa về trật tự hợp pháp có sức hấp dẫn đặc biệt với Kiều; chính nhu cầu kết thúc bất định khiến nàng dễ tin hơn."}},
2499:{voice:{kind:"LỜI KỂ CAO TRÀO",text:"Nhịp kể thu hẹp nhanh từ chính trị sang hậu quả thân thể và cái chết của Từ Hải."},knowledge:"Đến đây Từ và Kiều mới thấy đầy đủ hậu quả của thế cờ chiêu an; người đọc đã được chuẩn bị từ trước bằng cách kể về mưu kế nên trải nghiệm bi kịch như một điều đang khép lại không thể đảo ngược.",connections:[{type:"callback",target:2465,label:"Hậu quả của quyết định chiêu an",text:"Bi kịch ở đây là kết quả trực tiếp của việc chuyển từ thế chủ động sang tin vào bảo đảm của đối phương."}],psychology:{stage:"Sốc → mặc cảm → tuyệt vọng",text:"Cái chết của Từ Hải không chỉ là mất người chồng và chỗ dựa; Kiều còn phải sống với ý nghĩ mình đã góp phần thúc đẩy quyết định dẫn tới thảm họa."}},
3225:{voice:{kind:"LỜI NGƯỜI KỂ TÓM KẾT QUAN HỆ",text:"Người kể không nói rằng quá khứ được xóa sạch; ông xác nhận một hình thức hòa hợp mới sau khi Kiều và Kim đã tự đặt lại giới hạn của quan hệ."},knowledge:"Gia đình biết hai người đoàn tụ; Kiều và Kim còn biết chi tiết cuộc nói chuyện riêng và giới hạn thân thể mà họ đã thống nhất. Người đọc biết toàn bộ quãng mười lăm năm nên hiểu vì sao “đoàn tụ” không thể đồng nghĩa “trở về như cũ”.",connections:[{type:"callback",target:441,label:"Lời thề cũ",text:"Lời nguyện thời trẻ vẫn còn giá trị đạo đức, nhưng hình thức thực hiện đã thay đổi."},{type:"callback",target:723,label:"Món nợ Trao duyên",text:"Điều Kiều từng cố chuyển sang Vân cuối cùng được giải bằng sự thấu hiểu giữa chính Kiều và Kim, không bằng việc phục hồi nguyên trạng."}],psychology:{stage:"Chấp nhận và tự định nghĩa lại hạnh phúc",text:"Kiều không phủ nhận tình cũ, nhưng cũng không để tình cũ ép mình trở lại một hình thức quan hệ mà nàng không còn muốn."}},
3241:{voice:{kind:"LỜI NGƯỜI KỂ SUY NGẪM",text:"Câu chuyện nhân vật đã gần khép; giọng kể trở lại bình luận khái quát, giống cấu trúc sáu câu mở đầu."},connections:[{type:"callback",target:1,label:"Khép vòng mở đầu–kết thúc",text:"Tác phẩm trở lại câu hỏi đã nêu trước khi kể chuyện Kiều: đời người chịu bao nhiêu phần bởi mệnh và bao nhiêu phần bởi cách con người sống."}]},
3250:{variant:{base:"Cũng đừng trách lẫn trời gần trời xa",alternate:"Cũng đừng trách lẫn trời gần chẳng xa",effect:"Nếu đọc “trời gần trời xa”, câu thiên về khuyên đừng oán Trời theo bất cứ cách quy trách nào. Nếu đọc “trời gần chẳng xa”, câu có thể được hiểu như nhấn Trời ở gần chứ không xa — một hướng nghĩa khác hẳn, và chính bản khảo dị cũng đánh dấu chỗ này là khó xác quyết.",note:"Trang số hóa bản 1872 ghi nhận tự dạng gây tranh luận và đặt câu hỏi về cách ngắt/hiểu, vì vậy web nên hiển thị đây là dị bản chưa chắc chắn.",source:{label:"Bản 1872 – Digitizing Việt Nam",url:"https://www.digitizingvietnam.com/vi/our-collections/truyen-kieu/truyen-kieu-1872?page=163"}}},
3251:{voice:{kind:"LỜI NGƯỜI KỂ / KẾT LUẬN ĐẠO LÝ",text:"Sau khi nhắc trời và nghiệp, giọng kết thúc chuyển trọng tâm về “thiện căn” trong lòng người. Đây là bước điều chỉnh quan trọng: tác phẩm không đóng lại chỉ bằng thuyết định mệnh."},connections:[{type:"callback",target:2,label:"Từ chữ mệnh đến chữ tâm",text:"Mở đầu đặt tài đối diện mệnh; kết thúc đặt tâm cao hơn tài, chuyển câu hỏi từ cái con người phải chịu sang cái con người có thể lựa chọn trong cách sống."}]},
3253:{voice:{kind:"LỜI TÁC GIẢ TỰ HẠ GIỌNG",text:"Hai câu cuối hạ giọng từ triết lý lớn xuống lời tự khiêm về việc làm thơ. Sự chuyển giọng này tạo một kết thúc nhẹ sau toàn bộ bi kịch."},variant:{base:"Lời quê chắp nhặt dông dài",alternate:"Lời quê nhặt góp dông dài",effect:"“Chắp nhặt” gợi ghép những mảnh rời thành lời; “nhặt góp” nghiêng về thu lượm, gom góp. Cả hai đều giữ sắc thái tự khiêm, nhưng hình ảnh về hành động sáng tác hơi khác.",note:"Trang số hóa bản 1872 ghi “chắp nhặt” ở một số bản và “nhặt góp” ở ba bản Nôm cổ được đối chiếu.",source:{label:"Bản 1872 – Digitizing Việt Nam",url:"https://www.digitizingvietnam.com/vi/our-collections/truyen-kieu/truyen-kieu-1872?page=163"}}}
};
window.narrativeLayersForLine=function(lineNumber){return window.KIEU_NARRATIVE_LAYERS[lineNumber]||null;};
window.psychologyContextForLine=function(lineNumber){const timeline=window.KIEU_PSYCHOLOGY_TIMELINE;const index=timeline.findIndex(item=>lineNumber>=item.range[0]&&lineNumber<=item.range[1]);if(index<0)return {current:null,previous:null,next:null,index:-1,total:timeline.length};return {current:timeline[index],previous:timeline[index-1]||null,next:timeline[index+1]||null,index,total:timeline.length};};
