const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.join(__dirname,'..'),file=path.join(root,'js','cultural-layers.js');
assert.ok(fs.existsSync(file),'cultural layers module must exist');
let renders=0;
const sandbox={window:{},readerInsightPieces:()=>['base'],renderPage:()=>{renders++},escapeHtml:s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync(file,'utf8'),sandbox);
assert.ok(sandbox.window.KIEU_CULTURAL_LAYERS);
assert.strictEqual(typeof sandbox.window.culturalLayersForLine,'function');
const anchors=[1,41,43,55,83,164,631,647,665,690,1519,1525,3251];
for(const n of anchors)assert.ok(sandbox.window.culturalLayersForLine(n),`missing cultural anchor ${n}`);
const fields=new Set();for(const e of Object.values(sandbox.window.KIEU_CULTURAL_LAYERS))for(const k of ['technique','motif','culture','living','sourceCompare'])if(e[k])fields.add(k);
for(const k of ['technique','motif','culture','living','sourceCompare'])assert.ok(fields.has(k),`missing cultural layer type ${k}`);
assert.strictEqual(renders,1,'addon should rerender reader once after decorating');
const rows=sandbox.readerInsightPieces({n:647});
assert.ok(rows[0]==='base','must preserve existing reader insight rows');
assert.ok(rows.join('').includes('BÚT PHÁP'));
assert.ok(rows.join('').includes('BỐI CẢNH XÃ HỘI'));
assert.ok(rows.join('').includes('CÂU KIỀU TRONG ĐỜI SỐNG'));
console.log('cultural layers validation passed:',anchors.length,'anchors');
